const actionType = {
    GET_CATEGORY_PARENT: 'GET_CATEGORY_PARENT',
    GET_CATEGORY_BY_PARENT: 'GET_CATEGORY_BY_PARENT',
    GET_CATEGORY_SUB_CHILD: 'GET_CATEGORY_SUB_CHILD',
    GET_CATEGORY_DETAIL: 'GET_CATEGORY_DETAIL',
    GET_CATEGORY_LIST: 'GET_CATEGORY_LIST'
};

export default actionType;