const actionType = {
    POST_MENU_SHOW: 'POST_MENU_SHOW',
    POST_MENU_CLOSE: 'POST_MENU_CLOSE',
    POST_MENU_SHOW_MOBILE_PRIMARY: 'POST_MENU_SHOW_MOBILE_PRIMARY',
    POST_MENU_SHOW_MOBILE_SECONDARY: 'POST_MENU_SHOW_MOBILE_SECONDARY',
    POST_MENU_SHOW_MOBILE_CHILD: 'POST_MENU_SHOW_MOBILE_CHILD',
    POST_MENU_SHOW_MOBILE_SUB_CHILD: 'POST_MENU_SHOW_MOBILE_SUB_CHILD',
    POST_MENU_CLOSE_MOBILE: 'POST_MENU_CLOSE_MOBILE',
    POST_BACK_SECONDARY_MENU: 'POST_BACK_SECONDARY_MENU',
    POST_BACK_PRIMARY_MENU: 'POST_BACK_PRIMARY_MENU',
    POST_BACK_CHILD_MENU: 'POST_BACK_CHILD_MENU',
};

export default actionType;