const actionType = {
    POST_PRODUCT_VIEW: 'POST_PRODUCT_VIEW',
    GET_PRODUCT_LIST: 'GET_PRODUCT_LIST',
    GET_PRODUCT_DETAIL: 'GET_PRODUCT_DETAIL',
    GET_PRODUCT_LINK: 'GET_PRODUCT_LINK',
    GET_PRODUCT_DISCUSSION: 'GET_PRODUCT_DISCUSSION',
    GET_PRODUCT_PACKAGE: 'GET_PRODUCT_PACKAGE'
};

export default actionType;